adverts/urls.py
from django.conf.urls import url

from adverts.views import AdCreate, AdDetail, upload_media

urlpatterns = [
    url(r'^ad_create/$', AdCreate.as_view(), name='ad_create'),
    url(r'^view_more/(?P<pk>\d+)/$', AdDetail.as_view(), name='ad_detail'),
    url(r'^upload_media/$', upload_media, name='upload_media'),
]

fermanew/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from adverts.views import AdvertListView, copy_items
from companies.views import CompaniesListView
from fermanew import settings
from news.views import NewsListView

urlpatterns = [
    url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^admin/', admin.site.urls),
    # url(r'^search/', include('jet.urls', 'jet')),
    url(r'^ad/', include('adverts.urls', namespace='ad')),
    url(r'^$', AdvertListView.as_view(), name='main'),
    url(r'^copy_items/', copy_items, name='copy_items'),
    url(r'^news/', NewsListView.as_view(), name='news'),
    url(r'^companies/', CompaniesListView.as_view(), name='companies'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    # url(r'^search_results/$', AdvertListView.as_view, name='search')
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adverts/models.py
# coding=utf-8
from __future__ import unicode_literals

from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.core.exceptions import ValidationError
from django.db import models

# Create your models here.

ad_type = (('sell', 'Продаю'), ('buy', 'Куплю'), ('change', 'Меняю'), ('rent', 'Аренда'), ('offers', 'Услуги'))
Category_type = (
    ('stock_raising', 'Животноводство'), ('aviculture', 'Птицеводство'),
    ('pisciculture', 'Рыбоводство'), ('plant_growing', 'Растениеводство'),
    ('apiculture', 'Пчеловодство'), ('stern', 'Корма'),
    ('veterinary_drugs', 'Ветиренарные препараты'), ('the_property', 'Недвижимость'),
    ('production', 'Продукция'), ('equipment', 'Сельхоз техника и оборудование'),
    ('fertilizer', 'Удобрения'))


class CreateNewAdvert(models.Model):
    class Meta:
        verbose_name_plural = 'Объявления'
        verbose_name = 'Объявление'

    name = models.CharField(verbose_name='Name', max_length=255, null=True)
    email = models.CharField(verbose_name='Email', max_length=255, null=True)
    title = models.CharField(max_length=255, verbose_name='Заголовок', null=True)
    media = models.ManyToManyField('Media', verbose_name='Изображения', blank=True)
    advert_type = models.CharField(max_length=255, verbose_name='Тип объявления',
                                   choices=ad_type)
    categories = models.CharField(max_length=255, verbose_name='Категория',
                                  choices=Category_type, )
    text = RichTextUploadingField()
    date = models.DateField("Date", auto_now_add=True, null=True, blank=True)
    is_active = models.BooleanField(default=False, verbose_name='Подтверждено')
    agree_with_rules = models.BooleanField(default=False, verbose_name='Согласен с правилами')

    def __unicode__(self):
        # return 'ad object'
        return self.title


class Media(models.Model):
    class Meta:
        verbose_name = 'Медиа'
        verbose_name_plural = 'Медиа'

    media_file = models.FileField(verbose_name='Медиа файл')

    def get_absolute_url(self):
        return self.media_file.url

    def save(self, *args, **kwargs):
        super(Media, self).save(*args, **kwargs)

    def __unicode__(self):
        return str(self.media_file)

templates/base.html
<!doctype html>
{% load staticfiles %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>Ferma.kg</title>
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script type="text/javascript">
        function CleanFunc(obj) {
            $(obj).parent().css({
                "display": "none"
            });
            $(obj).parent().siblings().css({
                "margin-left": 0,
                "width": 100 + '%',
                "max-width": 100 + '%',
                "padding-left": 0
            });
            $(obj).parent().siblings().find('.more_block').css({
                'padding-left': 0
            })
        }
    </script>
</head>
<body>
<div class="mobile_hamburger"><a href="#" class="closed"><i class="fa fa-bars"></i></a></div>
<div class="mobile_menu" id="mobile_menu">
    <ul class="menu_list">
        <li><a href="{% url 'main' %}">главная</a></li>
        <li><a href="{% url 'news' %}">компании</a></li>
        <li><a href="#">новости</a></li>
    </ul>
</div>
<div class="white_back">
    <nav class="navbar navbar-toggleable-md navbar-light bg-faded ferma_nav">
        <div class="container">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item left_side_links">
                        <a class="nav-link" href="{% url 'main' %}">Главная<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item left_side_links">
                        <a class="nav-link" href="{% url 'news' %}">Новости<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item left_side_links">
                        <a class="nav-link" href="{% url 'companies' %}">Компании<span class="sr-only">(current)</span></a>
                    </li>
                </ul>
                <a class="navbar-brand m-auto" href="#"><img src="{% static 'img/logo.png' %}" alt=""></a>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link ad_advert" href="{% url 'ad:ad_create' %}">Добавить объявление<span
                                class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <form action="{% url 'main' %}">
                            <input type="search" name="search_words" placeholder="Поиск">
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</div>
{% block slider %}
    <div class="container-fluid main_slider">
        {% for i in slider %}
            <div class="slider_item">
                <div class="slider_item_caption container">
                    <div class="caption_title">{{ i.title }}</div>
                    <div class="caption_subtitle">{{ i.description }}</div>
                </div>
                <img src="{{ i.image.url }}" alt="">
            </div>
        {% endfor %}
    </div>
{% endblock %}
{% block content %}
{% endblock %}
<div class="container-fluid footer_container">
    <div class="container footer">
        <div class="row">
            <div class="col-md-2 col-sm-2 col-xs-12 left_side"></div>
            <div class="footer_content col-md-8 col-sm-12 col-xs-12 m-auto">
                <div class="row">
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 footer_cols">
                        <div class="col_content">
                            <div class="col_title">Айыл-чарба</div>
                            <div class="col_links_list">
                                <ul class="col_links p-0">
                                    <li><a href="{% url 'main' %}">Главная</a></li>
                                    <li><a href="{% url 'companies' %}">Компании</a></li>
                                    <li><a href="{% url 'news' %}">Новости</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 footer_cols">
                        <div class="col_content">
                            <div class="col_title">Контакты</div>
                            <div class="col_links_list">
                                <ul class="col_links p-0">
                                    <li>+996 (700) 222 932</li>
                                    <li>Whats App</li>
                                    <li>Viber</li>
                                    <li>Telegram</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 footer_cols">
                        <div class="col_content">
                            <div class="col_links_list">
                                <ul class="col_links p-0">
{#                                    <li class="nav-item">#}
{#                                        <a class="nav-link ad_advert" href="{% url 'ad:ad_create' %}">Добавить#}
{#                                            объявление<span class="sr-only">(current)</span></a>#}
{#                                    </li>#}
                                    <li class="nav-item">
                                        <form action="#">
                                            <input type="search" placeholder="Поиск">
                                        </form>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12 right_side"></div>
        </div>
    </div>
</div>
<script src="//cdn.ckeditor.com/4.7.1/basic/ckeditor.js"></script>
<script src="{% static 'js/main.js' %}"></script>
{% block custom_scripts %}
{% endblock %}
</body>
</html>

templates/companies.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <div class="container main_content">
        <div class="row">
            <div class="tab-content" style="width: 100%;">
                <div class="col-md-8 col-sm-12 col-xs-12 posts_container" style="display: block;margin: auto">
                    <div class="post clearfix">
                        {% for i in companies_ad %}
                            <div class="post_image col-md-4 col-sm-4 col-xs-12 no_padding">
                                <img src="{{ i.image }}" alt="" onerror="CleanFunc(this)">
                            </div>
                            <div class="post_describe col-md-8 col-sm-8 col-xs-12 no_padding">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="#">Компании</a></li>
                                    <li class="breadcrumb-item"><a href="#">{{ i.get_advert_type_display }}</a>
                                </ol>
                                <div class="date_block">
                                    <span>{{ i.date }}</span>
                                </div>
                                <div class="post_title">
                                    <h2>{{ i.title }}</h2>
                                </div>
                                <div class="post_describe_text" style="display: inline-block; vertical-align: top;">
                                    <p>{{ i.text|safe|truncatechars:'150'}}</p>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/footer.html
<div class="container-fluid footer_container">
    <div class="container footer">
        <div class="row">
            <div class="col-md-2 col-sm-2 col-xs-12 left_side"></div>
            <div class="footer_content col-md-8 col-sm-12 col-xs-12 m-auto">
                <div class="row">
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 footer_cols">
                        <div class="col_content">
                            <div class="col_title">Айыл-чарба</div>
                            <div class="col_links_list">
                                <ul class="col_links p-0">
                                    <li><a href="">Главная</a></li>
                                    <li><a href="">Компании</a></li>
                                    <li><a href="">Новости</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 footer_cols">
                        <div class="col_content">
                            <div class="col_title">Контакты</div>
                            <div class="col_links_list">
                                <ul class="col_links p-0">
                                    <li>+996 (700) 222 932</li>
                                    <li>Whats App</li>
                                    <li>Viber</li>
                                    <li>Telegram</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 footer_cols">
                        <div class="col_content">
                            <div class="col_links_list">
                                <ul class="col_links p-0">
                                    <li class="nav-item">
                                        <a class="nav-link ad_advert" href="#">Добавить объявление<span class="sr-only">(current)</span></a>
                                    </li>
                                    <li class="nav-item">
                                        <form action="#">
                                            <input type="search" placeholder="Поиск">
                                        </form>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12 right_side"></div>
        </div>
    </div>
</div>
<script src="//cdn.ckeditor.com/4.7.1/basic/ckeditor.js"></script>
<script src="js/main.js"></script>
</body>
</html>

templates/header.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="css/main.css">
    <title>Ferma.kg</title>
    <script src="js/jquery-3.1.1.min.js"></script>
    <script type="text/javascript">
        function CleanFunc(obj) {
            $(obj).parent().css({
                "display": "none"
            });
            $(obj).parent().siblings().css({
                "margin-left": 0,
                "width": 100 + '%',
                "max-width": 100 + '%',
                "padding-left": 0
            });
            $(obj).parent().siblings().find('.more_block').css({
                'padding-left': 0
            })
        }
    </script>
</head>
<body>
<div class="mobile_hamburger"><a href="#" class="closed"><i class="fa fa-bars"></i></a></div>
<div class="mobile_menu" id="mobile_menu">
    <ul class="menu_list">
        <li><a href="#">главная</a></li>
        <li><a href="#">компании</a></li>
        <li><a href="#">новости</a></li>
    </ul>
</div>
<div class="white_back">
    <nav class="navbar navbar-toggleable-md navbar-light bg-faded ferma_nav">
        <div class="container">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item left_side_links">
                        <a class="nav-link" href="#">Главная<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item left_side_links">
                        <a class="nav-link" href="#">Новости<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item left_side_links">
                        <a class="nav-link" href="#">Компании<span class="sr-only">(current)</span></a>
                    </li>
                </ul>
                <a class="navbar-brand m-auto" href="#"><img src="img/logo.png" alt=""></a>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link ad_advert" href="#">Добавить объявление<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <form action="#">
                            <input type="search" placeholder="Поиск">
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</div>

templates/new_advert.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <div class="container main_content">
        <div class="row">
            <div class="col-md-2 col-sm-2 col-xs-12 left_side">
                <div class="left_panel sticky-top">
                </div>
            </div>
            <div class="col-md-8 col-sm-8 col-xs-12 form_container">
                <form action="{% url 'ad:ad_create' %}" method="POST"
                        {#                      data-remove-uploaded-media-url="{% url 'ad:remove_uploaded_media' %}"#}
                      data-media-upload-url="{% url 'ad:upload_media' %}">
                    {% csrf_token %}
                    <div class="form_row"><label for="name">Ваше имя</label>{{ form.name }}</div>
                    <div class="form_row"><label for="email">Ваш Email</label>{{ form.email }}</div>
                    <div class="form_row"><label for="title">Введите заголовок</label>{{ form.title }}
                    </div>

                    <div class="form_row"><label for="advert_type">Тип объявления</label>{{ form.advert_type }}
                    </div>
                    <div class="form_row"><label for="advert_category">Выберите
                        категорию</label>{{ form.categories }}</div>
                    <div class="form_row"><label>Выберите картинку не более 1 мб</label><label for="advert_images"
                                                                                               class="advert_images">Выберите
                        файл</label><input type="file" name="images" id="advert_images" multiple>{{ form.images }}
                        {{ form.removed_images }}
                    </div>
                    <div class="form-row">
                        <div id="upload-images-row"></div>
                    </div>
                    <div class="form_row">{{ form.text }}</div>
                    <div class="form_row">{{ form.agree_with_rules }}<label for="agree_with_rules">Я
                        согласен с <a href="#">правилами</a></label></div>

                    <input type="submit" placeholder="Отправить">
                </form>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-3 right_side">
                <div class="right_banner sticky-top">
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block custom_scripts %}
    <script src="{% static 'ckeditor/ckeditor.js' %}"></script>
    <script src="{% static 'js/advert.js' %}"></script>
    <script type="text/javascript">
        CKEDITOR.replace('ad_text');
    </script>
{% endblock %}

templates/news_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <div class="container main_content">
        <div class="row">
            <div class="tab-content" style="width: 100%;">
                <div class="col-md-8 col-sm-12 col-xs-12 posts_container" style="display: block;margin: auto">
                    {% for i in news_ad %}
                        <div class="post clearfix">
                            <div class="post_image col-md-4 col-sm-4 col-xs-12 no_padding">
                                <img src="{{ i.image }}" alt="" onerror="CleanFunc(this)">
                            </div>
                            <div class="post_describe col-md-8 col-sm-8 col-xs-12 no_padding">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="#">Новости</a></li>
                                    <li class="breadcrumb-item"><a href="#">{{ i.get_advert_type_display }}</a>
                                </ol>
                                <div class="date_block">
                                    <span>{{ i.date }}</span>
                                </div>
                                <div class="post_title">
                                    <h2>{{ i.title }}</h2>
                                </div>
                                <div class="post_describe_text">
                                    <p>{{ i.text | safe |truncatechars:'50' }}</p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/no_results.html
{% extends 'base.html' %}
{% block content %}
{% endblock %}

templates/one_ad_page.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <div class="container main_content">
        <div class="row">
            <div class="col-md-2 col-sm-2 col-xs-12 left_side">
            </div>
            <div class="col-md-8 col-sm-12 col-xs-12 posts_container">
                <div class="one_ad_post clearfix">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Объявления</a></li>
                        <li class="breadcrumb-item"><a href="#">{{ ad.get_advert_type_display }}</a></li>
                        <li class="breadcrumb-item active">{{ ad.get_categories_display }}</li>
                    </ol>
                    <div class="date_block">
                        <span>{{ ad.date }}</span>
                    </div>
                    <div class="post_images no_padding">
                        {% for i in ad.media.all %}
                            <div class="img_rect"><img src="{{ i.media_file.url }}" alt="" onerror="CleanFunc(this)">
                            </div>
                        {% endfor %}
                    </div>
                    <div class="post_describe no_padding">
                        <div class="post_title">
                            <h2>{{ ad.title }}</h2>
                        </div>
                        <div class="post_describe_text">
                            <p>{{ ad.text |safe }}</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-3 right_side">
                <div class="right_banner sticky-top">
                    <a href="#"><img src="{% static 'img/banner2.png' %}" alt=""></a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/results.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <div class="container main_content">
        <div class="row">
            <div class="tab-content" style="width: 100%;">
                <div class="col-md-8 col-sm-12 col-xs-12 posts_container" style="display: block;margin: auto">
                    {% for i in results %}
                        {% if not forloop.counter|divisibleby:4 %}
                            <div class="post clearfix">
                                <div class="post_image col-md-4 col-sm-4 col-xs-12 no_padding">
                                    <img src="{{ i.media.first.media_file.url }}" alt="" onerror="CleanFunc(this)">
                                </div>
                                <div class="post_describe col-md-8 col-sm-8 col-xs-12 no_padding">
                                    <ol class="breadcrumb">
                                        <li class="breadcrumb-item"><a href="#">Объявления</a></li>
                                        <li class="breadcrumb-item"><a href="#">{{ i.get_advert_type_display }}</a>
                                        </li>
                                        <li class="breadcrumb-item active">{{ i.get_categories_display }}</li>
                                    </ol>
                                    <div class="date_block">
                                        <span>{{ i.date }}</span>
                                    </div>
                                    <div class="post_title">
                                        <h2>{{ i.title }}</h2>
                                    </div>
                                    <div class="post_describe_text">
                                        <p>{{ i.text | safe }}</p>
                                    </div>
                                    <div class="more_block">
                                        <a href="{% url 'ad:view_more' i.id %}" class="show_more">показать</a>
                                        <a href="#" class="reply"><i class="fa fa-reply" aria-hidden="true"></i></a>
                                    </div>
                                </div>
                            </div>
                        {% else %}
                            <div class="banner_post clearfix">
                                <img src="{{ i.image.url }}" alt="">
                            </div>
                        {% endif %}
                    {% endfor %}
                    <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-center mt-4">
                            <li class="page-item">
                                {% if pages.has_other_pages %}
                                    {% if pages.has_previous %}
                                        <a class="page-link" href="?page={{ pages.previous_page_number }}"
                                           aria-hidden="true">&laquo;</a>
                                    {% endif %}
                                    </a>
                                    </li>
                                    {% for i in pages.paginator.page_range %}
                                        {% if pages.number == i %}
                                            <li class="page-item"><a class="page-link"
                                                                     href="?page={{ i }}">{{ i }}</a></li>
                                        {% else %}
                                            <li class="page-item"><a class="page-link"
                                                                     href="?page={{ i }}">{{ i }}</a></li>
                                        {% endif %}
                                    {% endfor %}
                                    {% if pages.has_next %}
                                        <a class="page-link" href="?page={{ pages.next_page_number }}"
                                           aria-hidden="true">&raquo;</a>
                                    {% endif %}
                                {% endif %}
                            </a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/slider.html
<div class="container-fluid main_slider">
    <div class="slider_item">
        <div class="slider_item_caption">
            <div class="caption_title"></div>
            <div class="caption_subtitle"></div>
        </div>
        <img src="img/cow.jpeg" alt=""></div>
    <div class="slider_item">
        <div class="slider_item_caption">
            <div class="caption_title"></div>
            <div class="caption_subtitle"></div>
        </div>
        <img src="img/cow.jpeg" alt=""></div>
    <div class="slider_item">
        <div class="slider_item_caption">
            <div class="caption_title"></div>
            <div class="caption_subtitle"></div>
        </div>
        <img src="img/cow.jpeg" alt=""></div>
    <div class="slider_item">
        <div class="slider_item_caption">
            <div class="caption_title"></div>
            <div class="caption_subtitle"></div>
        </div>
        <img src="img/cow.jpeg" alt=""></div>
</div>